name: Docker Build

on:
  push:

jobs:

  build_and_push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Extract Branch Name
      shell: bash
      run: |
          branchName=${GITHUB_REF#refs/heads/}
          branchName=$(echo "$branchName" | tr '[:upper:]' '[:lower:]')
          branchName=$(echo "$branchName" | sed 's/\//_/g')
          if [ "$branchName" = 'main' ]; then tagname='latest'; else tagname=$branchName; fi
          echo "::set-output name=tagname::$(echo $tagname)"
      id: extract_branch
    - name: Build and publish the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/buttercheetah/gamekit:${{ steps.extract_branch.outputs.tagname }}
        docker push ghcr.io/buttercheetah/gamekit:${{ steps.extract_branch.outputs.tagname }}
